#!/bin/bash -x

   echo "check the user first name"
   pat="^[[:upper:]]{3,}[a-z0-9]*|[[:upper:]]{1,}[a-z0-9]{2,}"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "valid";
   else
     echo "invalid";
   fi

