#!/bin/bash -x

   echo "check the user first name"
   pat="^[[:upper:]]{3,}[a-z0-9]*|[[:upper:]]{1,}[a-z0-9]{2,}"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "First name is valid";
   else
     echo "First name is invalid";
   fi 

   echo "check the user Last name"
   pat="^[[:upper:]]{3,}[a-z0-9]*|[[:upper:]]{1,}[a-z0-9]{2,}"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "Last name is valid";
   else
     echo "Last name is invalid";
   fi
   
   echo "check the email pattern"
   pat="^[0-9a-zA-Z]+([._+-][0-9a-zA-z]+)?@[0-9a-zA-Z]+.[a-zA-Z]{2,4}([.][a-zA-Z]{2})?$"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "it's a valid email";
   else
     echo "it's a invalid email";
   fi

   echo "check the predefined mobile pattern"
   pat="^[0-9]{2}[ ]{1}[0-9]{10}$"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "valid mobile format";
   else
     echo "invalid mobile format";
   fi

